GET http://localhost:5123

###
GET http://localhost:5123/todos

###
GET http://localhost:5123/todos/124

###
POST http://localhost:5123/todos
Content-Type: application/json

{
    "id": 126,
    "name": "Estudar WEB Api 2",
    "dueDate": "2024-08-08T00:00:00",
    "isCompleted": false
}

###
DELETE http://localhost:5123/todos/124
Content-Type: application/json